### ISSUE TITLE
Postgresql compatibility issue with `default`

### ISSUE THREAD

**Issue by pongraczi** [laravel-enso/PermissionManager#12]
https://github.com/laravel-enso/PermissionManager/blob/12d89fcfd20fe1b1e1dceb79d36efdc634c53c05/src/app/Http/Controllers/PermissionTableController.php#L21

**`default`** should be **"default"** or just plain **default**  
I checked it with PHP 7.2 + Postgresql 9.6

**Comment by aocneanu** [comment]
Hi,

It went through a transition, first it was `default`(reserved word in MySql)  instead of `permissions.default`, but in this form we can drop the "grave accent", or whatever it's name is.

Feel free to make a PR :)

**Comment by pongraczi** [comment]
Completed.
