### ISSUE TITLE
Create Resource form always creating all resource even switch off unneccesary permissions

### ISSUE THREAD

**Issue by shonhor22** [laravel-enso/PermissionManager#14]
This is  a **bug  request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

I have to create only selectoptions permission. In Create Resource form only one field checked. but after saving it will create all unneccesary permissions.

**Comment by aocneanu** [comment]
closed with laravel-enso/PermissionManager@b24a53c
