### ISSUE TITLE
User-level permission expansion/override

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/PermissionManager#15]
This is  a **feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

The bulk of our permissions are defined on a _general_ role basis; however (as we have a granular rollout of new features, amongst other reasons) we need to define/override certain permissions on a user-level

#### Base

Add a `permission_user` pivot that is also checked along with `permission_role` to verify permission.

This includes introducing a permissions() object on the user directly; that will check the role's permissions too (to remain DRY)

TODO: 
- [ ] add `permissions()` relationship in the User Model (similar to the one in the Role Model)
- [ ] write accompanying db migration (new `permission_user` table)
- [ ] update from `role->permissions()` to user-based required in:
	- [ ] menumanager: MenuTree's setPermissions()
	- [ ] core: AppState's routes()
	- [ ] searchable: Finder's permissions()
	- [ ] permissionmanager: AuthServiceProvider's boot() (`access-route`)
- [ ] Investigate implications for ConfigWriter (in rolemanager)

#### Expansion/optional (depending on your feedback)

- [ ] Add a flag to above pivot indicating if it's a allow or deny (to allow overriding in both directions.
- [ ] implement permission-edit-UI coupled to user (our implementation only requires code-wise changes; but since the UI is already there for roles it shouldn't be a big extra to implement this; making the feature more solid for more use cases)

Note that I'll be starting on this first thing next week, hopefully as a contribution to the framework as I believe there's many use cases for this (depending on your comments, will otherwise just override what I need)

**Comment by aocneanu** [comment]
At the first sight having roles and then overriding permissions seems spaghetti.

I'm trying not to jump to conclusions, so please help me to better understand the business need.

>The bulk of our permissions are defined on a general role basis; however (as we have a granular rollout of new features, amongst other reasons) we need to define/override certain permissions on a user-level

How many users do you have in the app? How many roles? Give me a few 'rollout feature' examples that build the case.

**Comment by aocneanu** [comment]
I got lost after this

>We have about 1000 users logging in, with about 5 roles total

In my opinion having the option to add / suppress permission for 1000 users it's not something that I would pursuit.

Let's say that your roles are the ones below:

1. Superadmin - this has all the permissions
2. Admin
3. Supervisor
4. PM
5. User

You have lots of features that you roll out every week for every "subset" of users. 

Just create 4 new roles with identical permissions to the original ones:

6. Admin beta tester
7. Supervisor beta tester
8. PM beta tester
9. User beta tester

Move the users that do the tests / explaining the tools to the beta tester roles.
Once you have new features, add the permissions first to the beta testers, and when they are mature also to the original roles.

BOOM.

**Comment by jlsjonas** [comment]
The issue is that feature A might roll out to subset 1 while feature B might rollout to subset 2; and it might take months (or in some cases years) before _everyone_ has all features. This is due to existing business logic and not something that I'll be able to change,

The granularity could be limited to _permission groups_ instead; but those aren't tied into anything currently.

+
>especially as there's business logic tied into the role (different role = different actions)

we have to do id/name based checks on roles to give different actions; creating a role for every possible feature combination would cause an even bigger mess in that logic.


I'm not in favor of having user-level permissions like this either but it's business logic that I'm not in a position to change; so there's no way around it for us.

(the "multi-year" differences could be turned into a couple extra roles; but this can't easily happen for the rollout as it's tied into external factors with random orders; that would easily introduce bigger issues)

Also to clarify: those who do the explaining are explaining it on the account of the user; and once explained it should be available for that user.
Simultaneously, it's possible that a different group is doing the same for a different feature. 

I considered what you suggested at first; but it would easily get too complicated that way (+ the shown role would look weird as it would need a programmatic definition of the tool subset so it can be dynamically applied on login; tied into AD/NAV)

**Comment by aocneanu** [comment]
I guess we can close this, or you could try to move it on your fork.

**Comment by jlsjonas** [comment]
i.e. not to be considered for the framework? 👌 🔒

**Comment by jlsjonas** [comment]
I'll keep you posted (might take a while as we'll only need it at a later stage; but we will definitely need a solution for it by early next year)
