### ISSUE TITLE
Table search & role configure broken (not fully migrated?)

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/PermissionManager#17]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
The search in permissions seems to be broken; reproduced on https://www.laravel-enso.com/system/permissions/

![image](https://user-images.githubusercontent.com/932193/51316886-4cd44480-1a56-11e9-825c-0464a4d7d529.png)

![image](https://user-images.githubusercontent.com/932193/51316898-55c51600-1a56-11e9-9c6a-fce26e87a07b.png)

### Steps to Reproduce
try to make any search on https://www.laravel-enso.com/system/permissions/

### Expected behavior
Correct filtering

### Actual behavior
blank result set

**Comment by aocneanu** [comment]
fixed in the last commit / tag in vdt

**Comment by jlsjonas** [comment]
That fixed it indeed, however https://www.laravel-enso.com/system/roles/1/configure seems broken by a similar change (adding it here as it's likely related)

**Comment by aocneanu** [comment]
it also fixed but from the last commit / tag in rolemanager. About the same time as vdt:)

**Comment by jlsjonas** [comment]
😁 
Closing this issue on next Enso update (i.e. when laravel-enso.com received the updates)?

**Comment by aocneanu** [comment]
done
